<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Food Access in the Midwest versus the Northeast</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Stat4</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data">Introduction and Data</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review">Literature Review</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Food Access in the Midwest versus the Northeast</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction-and-data" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-data">Introduction and Data</h2>
<p>We are interested in the topic of food accessibility (defined as the ability to access healthy and affordable foods) in the US and how factors such as family income, vehicle availability, and neighborhood characteristics such as average income and availability of public transportation impact food accessibility. Our data is from the United States Department of Agriculture’s Economic Research Service (2010), which contains information about each US county’s ability to access supermarkets. Though there is no available information on how the USDA ERS collected this particular data set, the USDA ERS generally collects data in the following ways: surveys, administrative data, census data, and remote sensing. Given the variables of the food access data, it is likely that the USDA ERS used a combination of surveys and census data to collect information. This data set contains information about people’s ability to access supermarkets in the US. There are multiple factors that are taken into account. Each of these factors negatively or positively affects people’s ability to access healthy food. Some people live further away or closer to supermarkets, have cars, are of different income groups, and are of different age demographics. Each of these factors contribute to differences in food accessibility.</p>
<p>Background on the Topic of Food Insecurity: (https://health.gov/healthypeople/priority-areas/social-determinants-health/literature-summaries/food-insecurity). This article defines food insecurity as a condition in which an individual has limited access to adequate food. A lot of households are affected by this. It can be long-term or temporary and is influenced a variety of factors, such as by income, employment, race/ethnicity, and disability. High unemployment rates in low-income populations make it even more difficult to have sufficient food access. In 2020, Black households’ food insecurity percentage was 21.7, which was 2 times greater than the national average. Possible reasons include neighborhood conditions, physical access to food, and lack of transportation. People who live in low-income neighborhoods may have less access to supermarkets. Predominantly Black and Hispanic neighborhoods have fewer high-quality markets than predominantly white neighborhoods. Food insecurity could lead to negative health problems and there are studies which demonstrate how food insecurity may increase risk for obesity and developmental/mental health problems in children.</p>
<p>Definitions of Key Variables: County: County Name Population: Population Count from 2010 Census State: State Name Housing Data. Total Housing Units: Occupied Housing Unit Count from 2010 Census Vehicle Access. 10 Miles: Housing Units without Vehicle Count Beyond 10 Miles from Supermarket Low Access Numbers.Low Income People. 10 Miles: Low income population count beyond 10 miles from supermarket Low Access Numbers.People.10 Miles: Population count beyond 10 miles from supermarket Low.Access Numbers.Seniors.10 Miles: Seniors population count beyond 10 miles from supermarket. There are a mix of quantitative and qualitative variables.</p>
<p>Research Question:</p>
<p><strong>Is the Midwest more impacted by being low income and being beyond 10 miles from a supermarket compared to the Northeast? If there is a difference between those two regions, and if so, what variables contribute to that?</strong> Our target population for this question are individuals living in the Northeast and Midwest area of the US, as the Northeast is generally more urban and the Midwest is generally more rural and agricultural-based. We hope to bring awareness to potentially significant differences in food access because everyone should have access across the US, regardless of geographic location. This question is original because it is focusing on a “10 mile” range specifically. This research question will be answered using a hypothesis test and confidence intervals. <strong>Given our background research on the Midwest and the Northeast regions, we hypothesize that the Midwest will be mostly impacted by having a greater proportion of low income population count beyond 10 miles from supermarkets.</strong> We will conduct a hypothesis test to test this hypothesis. We are also exploring an additional question to support our hypothesis test: What is the confidence interval for the true mean proportion of low income individuals that live beyond 10 miles from a supermarket in the Northeast? In the Midwest?</p>
<p>Definitions of Key Variables: There are a mix of quantitative and qualitative variables. Qualitative Variables: County: County Name State: State Name Housing Data Quantitative Variables: Population: Population Count from 2010 Census Housing Data. Total Housing Units: Occupied Housing Unit Count from 2010 Census Vehicle Access. 10 Miles: Housing Units without Vehicle Count Beyond 10 Miles from Supermarket Low Access Numbers.Low Income People. 10 Miles: Low income population count beyond 10 miles from supermarket Low Access Numbers.People.10 Miles: Population count beyond 10 miles from supermarket Low.Access Numbers.Seniors.10 Miles: Seniors population count beyond 10 miles from supermarket.</p>
<p>Research Question: <strong>Does the Midwest or Northeast have a higher amount of individuals who have low access to super markets and have low income and are beyond 10 miles away from a supermarket? Which specific variables contribute to this difference?</strong> Our target population for this question are individuals living in the Northeast and Midwest area of the US, as the Northeast is generally more urban and the Midwest is generally more rural and agricultural-based. We hope to bring awareness to potentially significant differences in food access because everyone should have access across the US, regardless of geographic location. This question is original because it is focusing on a “10 mile” range specifically. This research question will be answered using a hypothesis test and confidence intervals. <strong>Given our background research on the Midwest and the Northeast regions, we hypothesize that the Midwest will be mostly impacted by having a greater proportion of low income population count beyond 10 miles from supermarkets.</strong> We will conduct a hypothesis test to test this hypothesis. We are also exploring an additional question to support our hypothesis test: What is the confidence interval for the true mean proportion of low income individuals that live beyond 10 miles from a supermarket in the Northeast? In the Midwest?</p>
<p>Data cleaning: We first mutated the data set to categorize each state into their respective region (Midwest, Northeast, Southwest, Southeast, and West). We also mutated the data to include the proportion of low income population count beyond 10 miles from supermarket, the proportion of seniors population count beyond 10 miles from supermarket, and housing units without vehicle count beyond 10 miles from supermarket (all these are over occupied housing unit count from 2010 census).</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Graph%201%20relationship%20between%20low%20income%20and%20vehicle%20access%20in%20the%20Midwest%20&amp;%20Northeast-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We wanted to see if having no vehicle access and being beyond 10 miles from a supermarket is associated with being low income and being 10 miles from a market. Therefore, we created a scatter plot. There is a positive relationship between the proportion of having no vehicle and being beyond 10 miles away from a market and the proportion of low income who are 10 miles away from a supermarket for both regions. As the proportion of no vehicle access who are 10 miles away increases, so does the proportion for individuals who are low income and are 10 miles away from a market.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Graph%202%20relationship%20between%20low%20income%20and%20seniors%20in%20the%20Midwest%20&amp;%20Northeast-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We wanted to see if being a senior who lives beyond 10 miles from a supermarket is associated with being low income and being 10 miles from a market. Therefore, we created a scatter plot. There is a positive relationship between the proportion of being a senior and living 10 miles away from a market and the proportion of low income who are 10 miles away from a supermarket for both regions. As the proportion of being a senior and living 10 miles away increases, so does the proportion for individuals who are low income and are 10 miles away from a market.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Graph%203%20Density-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Explanation for Density Curve: Given housing units without vehicle access beyond 10 miles from a supermarket, the density curves for both regions have a similar shape, with the Midwest having a slightly higher density of lower values of vehicle access compared to the Northeast. There is some overlap between the two regions in terms of the distribution of vehicle access, indicating that there are some areas in the Midwest with similar vehicle access to supermarkets as some areas in the Northeast.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/ROC%20Curves-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/ROC%20Curves-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.718</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.718</code></pre>
</div>
</div>
<p>Based on both ROC Curves, the AUC for both is around ~0.717, indicating a strong predictor value for the given region.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">Literature Review</h2>
<p>https://pubmed.ncbi.nlm.nih.gov/30792950/ This study examines the relationship between access to a personal vehicle and diet, food insecurity, and physical activity among public housing residents, which are typically low-income, urban populations. The study conducted a cross-sectional survey of randomly selected households within two public housing communities in Baltimore, MD. The study used Poisson regression with robust error variance to estimate relative risk ratios adjusted for demographics and perceived environmental factors.</p>
<p>The independent variable was whether or not the resident had access to a personal vehicle which the dependent variables were ‘high’ fruit &amp; vegetable intake (&gt;= 6.7 servings/day), ‘high’ added sugar intake (&gt;+ 39.9 tsp/day), food insecurity, and being physically active. The sample included 265 adults with mean age of 45 years, 86% women, and 96% African-American. Only 42% had access to a vehicle.</p>
<p>The study found that there were no significant associations that existed between personal vehicle access with diet or physical activity outcomes. However, the study found that access to a personal vehicle was associated with significantly lower risk of food insecurity (RR 0.76, 95% CI 0.63-0.92, p &lt; 0.01). There was a significant association between personal vehicle access and lower risk of food insecurity.</p>
<p>In connection to the article, our research explores other factors beyond transportation (specifically vehicle access) such as family income and the availability of public transportation. Our research also expands across both urban and rural areas in the United States while the article focuses exclusively on Baltimore, MD. Moreover, our research attempts to understand the relationship between various geographical regions, accounting for numerous variables.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>First, in order to clean our data and prep for the data analysis and models, different region vectors were created in order to merge with the original food_access data sets. Since our research question involves regions and the original data sets does not include that, multiple mutate with case_when was used to clean and modify the data.</p>
<p>By quantifying and visualizing the relationship between the variables in the Midwest and Northeast, the sample mean difference is extracted from the given regions. This is used to run a hypothesis test in order to answer our research question because if the p-value is less than alpha, then we can reject the null hypoythesis. This would help answer our research question as it would show which region is impacted more by taking the mean of the proportions of low income people 10 miles away from the supermarket without a vehicle. Based on the results of the hypothesis test, we run a confidence interval in order to see where the true mean lies in each region.</p>
<p>In order to find which variables contribute to the Midwest region being more impacted by low income and no transportation, a linear regression model is used as the low income people without vehicle access beyond 10 miles from a supermarket is the explanatory, and the number of people living in housing quarters as the response variable. This would be the best variable to use in the linear regression because the other data refers to children, seniors, and other varying amounts of vehicle distance. Therefore, housing group quarters population would be the best variable to use in this linear regression model and would help solidify the second part of the research question.</p>
<p>In order to explore the basic relationships, first some exploratory data analysis was conducted. By quantifying and visualizing the relationship between the variables in the Midwest and Northeast, the sample mean difference is extracted from the given regions. This is used to run a hypothesis test in order to answer our research question. This would help answer our research question as it would show which region is impacted more by taking the mean of the proportions of low income people 10 miles away from the supermarket without a vehicle. Based on the results of the hypothesis test, we run a confidence interval in order to see where the true mean proportion lies in each region.</p>
<p>We choose a hypothesis test because it helps answer our research question if the Midwest or Northeast is more impacted by being low income and living 10 miles away from a supermarket. We hypothesize that compared to the Northeast, the Midwest will be mostly impacted by having a greater proportion of low income population count beyond 10 miles from supermarket. Our null hypothesis is that the true mean proportional difference for low income and beyond 10 miles from the supermarket between the Midwest and Northeast is equal to 0. Our alternate hypothesis is that the true mean proportional difference for low income and beyond 10 miles from the supermarket between the Midwest and northeast is greater than 0. Using the resulting p-values from our test, we can see if the Midwest is more impacted or if there is no difference between the two. We will be using simulation based techniques. We will permute all observations together, distribute them into two new groups, calculate the new sample means for each group, and lastly subtract the new sample means. This will be done 5000 times.</p>
<p><strong>Hypothesis Test</strong></p>
<p><span class="math inline">\(H_o\)</span>: <span class="math inline">\(\mu_{Midwest} - \mu_{Northeast} = 0\)</span></p>
<p>Null Hypothesis: The true mean proportional difference for low income and beyond 10 miles from the supermarket between the Midwest and northeast is equal to 0.</p>
<p><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_{Midwest} - \mu_{Northeast} &gt; 0\)</span></p>
<p>Alternative Hypothesis: The true mean proportional difference for low income and beyond 10 miles from the supermarket between the Midwest and northeast is greater than 0.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
   mean
  &lt;dbl&gt;
1 0.112</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    mean
   &lt;dbl&gt;
1 0.0167</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09569124</code></pre>
</div>
</div>
<p>The sample mean proportion of low income population count beyond 10 miles from the supermarket is .11 for the Midwest region and .017 for the Northeast region.</p>
<p><span class="math inline">\(\bar{x_{Midwest}} = .11\)</span></p>
<p><span class="math inline">\(\bar {x_{Northeast}} = .017\)</span></p>
<p>The observed mean proportion difference between <span class="math inline">\(\bar{x_{Midwest}}\)</span> and <span class="math inline">\(\bar{x_{Northeast}}\)</span> = 0.09569124$</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Visualization-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>mapping: xintercept = ~xintercept 
geom_vline: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>Conclusion: The probability of observing a true mean proportional difference of 0.09569124 between the Midwest and the Northeast for low income population count beyond 10 miles from the supermarket is ~ 0, given that the true mean proportional difference for low income and beyond 10 miles from the supermarket between the Midwest and Northeast is equal to 0 the difference is equal to 0. Because p = ~ 0 alpha = .05, we reject the null hypothesis. We have strong evidence to conclude the alternate hypothesis. Based on this test, we can answer our research question and conclude that the Midwest has a higher amount of individuals who are low income and beyond 10 miles away from a supermarket.</p>
<p><strong>Confidence Interval: True mean proportion for Midwest</strong></p>
<p>After our result from the hypothesis test, we wanted to further support that the Midwest is more impacted than the Northeast. Therefore, we will be creating two confidence intervals to determine the true mean proportion for low income and living 10 miles beyond a supermarkets. We will then compare these intervals. The interval with a higher proportion interval will have a higher amount of individuals who are low income and live 10 miles beyond a supermarket. We will be used simulation based techniques because we are sampling with replacement, calculating the new resampled mean, and then we will be repeat that process 5000 times.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,000
Columns: 2
$ replicate &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ stat      &lt;dbl&gt; 0.1144171, 0.1136144, 0.1131544, 0.1066412, 0.1130759, 0.120…</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1 0.103 0.123</code></pre>
</div>
</div>
<p>We are creating a histogram to see the distribution of re-samples from our original data for Midwest. We also have lines that represent our confidence interval.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Visualization%20Midwest-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: We are 95% confident that the true mean proportion of low income individuals that live beyond 10 miles from a supermarket in the Midwest is between 0.102609 and 0.1226445.</p>
<p><strong>Confidence Interval: True mean proportion for Northeast</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,000
Columns: 2
$ replicate &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ stat      &lt;dbl&gt; 0.01381593, 0.01676433, 0.01266810, 0.01101073, 0.01092749, …</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   lower  upper
   &lt;dbl&gt;  &lt;dbl&gt;
1 0.0114 0.0230</code></pre>
</div>
</div>
<p>We are creating a histogram to see the distribution of re-samples from our original data for Northeast. We also have lines that represent our confidence interval.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/Visualization%20Northeast-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: We are 95% confident that the true mean proportion of low income individuals that live beyond 10 miles from a supermarket in the Northeast is between 0.01155406 and 0.02294395.</p>
<p><strong>Regression Models</strong></p>
<p><span class="math inline">\(p\)</span> = low income individuals who are 10 miles away from supermarkets/ housing units <span class="math inline">\(p_v\)</span> = no vehicle access beyond 10 miles from a supermarket population count/ housing units <span class="math inline">\(p_s\)</span> = seniors beyond 10 miles from a supermarket population count/ housing units</p>
<p>Adjusted r-squared value for linear regression model fitting <span class="math inline">\(p\)</span> to <span class="math inline">\(p_v\)</span> within Midwest region</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6773385</code></pre>
</div>
</div>
<p>Adjusted r-squared value for linear regression model fitting <span class="math inline">\(p\)</span> to <span class="math inline">\(p_s\)</span> within Midwest region</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7553672</code></pre>
</div>
</div>
<p>Adjusted r-squared value for additive linear regression model fitting <span class="math inline">\(p\)</span> to <span class="math inline">\(p_v\)</span> and <span class="math inline">\(p_s\)</span> within Midwest region</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8534947</code></pre>
</div>
</div>
<p>Adjusted r-squared value for interactive linear regression model fitting <span class="math inline">\(p\)</span> to <span class="math inline">\(p_v\)</span> times <span class="math inline">\(p_s\)</span> within Midwest region</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8715612</code></pre>
</div>
</div>
<p>After seeing the results to our hypothesis test and CI, we conclude that the Midwest has a higher amount of individuals who are low income and 10 miles beyond a supermarket. We used a linear regression to see which variables affect that, which answers the second part of our research question. We choose the variables proportion of seniors and no vehicle access being 10 miles away. First, we fit those variables individually. Then we looked at their adjusted r-squared values. The linear regression with the proportion of seniors had a higher adjusted r-squared value. So then we included an additive and interactive component with the proportion of having no vehicle access. The interactive model had a higher adjusted r-squared value.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>Based on the exploratory data analysis, the first graph is a density plot that shows the distribution of vehicle access beyond 10 miles for both the Midwest and Northeast regions. The graph is relevant as it shows the difference in the distribution of vehicle access between the two regions. For instance, the Midwest region appears to have a higher density of vehicle access beyond 10 miles than the Northeast region. The third and fourth ROC graph curves represent where the x-axis represents the false positive rate, while the y-axis represents the true positive rate. The graph is relevant as it shows the ability of the logistic regression model to distinguish between the Midwest and Northeast regions based on vehicle access beyond 10 miles. For instance, the higher the AUC, the better the model is at discriminating between the two regions. They both have an AUC of around 0.717, indicating a high prediction rate based on the regions and no vehicle access. This helps quantify the strength of the relationships and set up for the hypothesis test.</p>
<p>Conclusion of Hypothesis Test: The probability of observing a 0.09569124 true mean proportional difference between the Midwest and the Northeast and low income population count beyond 10 miles from the supermarket is approximately 0, given that the difference is equal to 0, is p = ~0. Because p = 0 $alpha$ = .05, we reject the null hypothesis that the true mean proportional difference between the Midwest and low income population count beyond 10 miles from the supermarket is equal to 0. We have strong evidence to conclude the alternative, which supports our hypothesis that the Midwest has more low income populations 10 miles away from supermarkets than the Northeast.</p>
<p>might delete &lt;- Interpretation: We are 95% confident that the true mean proportion of low income individuals that live beyond 10 miles from a supermarket in the Midwest is between 0.102609 and 0.1226445. (Other confidence)</p>
<p>add &lt;- key takeaway from CIs</p>
<p>The two explanatory graphs in the Introduction support our claim that the Midwest is more impacted as the proportions for the Midwest reach higher numbers for the proportion of low income who are 10 miles away. Moreover, it shows that having no vehicle access contributes to this problem, supporting our claim that the Midwest is more impacted by not having reliable access to transportation compared to more urban areas like the Northeast.</p>
<p>Linear regression: After we rejected our null hypthesis, we created a linear regression to see which variables affect low income and being 10 miles away for the Midwest specifically. We found that the best model was when the proportion of seniors and proportion of no vehicle access being 10 miles away interacted with each other. This model had the highest adjusted r squared value (0.8715612). A higher r-squared value indicates a higher amount of variability being explained by our model. Therefore, our adjusted r-squared value supports that our interactive model is a good fit for our data. This value answers the second part of our research question. Individiuals who are a senior and have no vehicle access and being 10 miles beyond a supermarket contribute to low income and being 10 miles beyond a supermarket in the midwest.</p>
<p>These two graphs support our claim that the Midwest is more impacted as the proportions for the Midwest reach higher numbers for the proportion of low income who are 10 miles away. Moreover, it shows that having no vehicle access contributes to this problem, supporting our claim that the Midwest is more impacted by not having reliable access to transportation compared to more urban areas like the Northeast.</p>
<p>Linear regression: We created a linear regression to see which variables have a strong association with the variable “Low Access Numbers. Low Income People. 10 Miles” which describes the low income population count beyond 10 miles from supermarket. We found that the best model was when the proportion of seniors and proportion of no vehicle access being 10 miles away interacted with each other. This model had the highest adjusted r-squared value (0.8715612). A higher adjusted r-squared value indicates a higher amount of variability being explained by our model. Therefore, our adjusted r-squared value supports that our interactive model is a good fit for our data. This value answers the second part of our research question. Individuals who are a senior and have no vehicle access being 10 miles beyond a supermarket contribute to low income and being 10 miles beyond a supermarket in the Midwest.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>We have learned from our research question that the Midwest has a smaller true mean proportion of low-income households that have vehicle access to a supermarket 10 miles away compared to the Northwest, with a p-value of ~0 when assuming that there is no difference.<br>
The analysis included the state with the most no vehicle access which was District of Columbia. However, the District of Columbia only has one row of collected data and therefore, we could not perform an accurate linear regression in order to quantify the relationship between the variables contributing to the no vehicle access and low income. This could be a limitation of the analysis and therefore combining more data from other data sets would help further strengthen this analysis. Not much could be analyzed from housing quarters and no vehicle access, and more could be gleamed from combining other data sets. There could be more influential variables affecting the low access, low income people living 10 miles away. However, only much could be done using this data set.</p>
<p>Also, since this data set was collected by census and surveys, there could be a sample size and representation bias. Surveys often rely on a sample of people to represent a larger population. If the sample size is too small or not representative of the population of interest, the results may not be generalization to the broader population. This data set is also from 2010, which is relatively outdated compared to 2023.</p>
<p>Some potential areas of future interest include: relationship between food access and health outcomes, or socioeconomic factors. With the data on health outcomes available in the data set, researchers could explore whether living in an area with limited food access is associated with poorer health outcomes, such as higher rates of obesity, diabetes, or heart disease. The data set could expand to include information on income, education level, and race/ethnicity. Researchers could explore whether these factors are associated with differences in food access, and if so, which policy interventions might be effective in addressing these disparities.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>